name: kafka-a-new-hope

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-kraft
    ports:
      - 9101:9101
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP='CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      - KAFKA_ADVERTISED_LISTENERS='PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_PROCESS_ROLES='broker,controller'
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS='1@kafka:29093'
      - KAFKA_LISTENERS='PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      - KAFKA_INTER_BROKER_LISTENER_NAME='PLAINTEXT'
      - KAFKA_CONTROLLER_LISTENER_NAMES='CONTROLLER'
      - CLUSTER_ID='MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - ./kafka:/bitnami/kafka # Mount a host directory to the container

  client:
    build:
      context: ./simulate-call-flows
    depends_on:
      - api
    command: ["npx", "ts-node", "parallelSimulateCallEvents.ts", "50"]
    volumes:
      - ./simulate-call-flows:/usr/src/app
